### ISSUE TITLE
eth-crypto confligs with the truffle package

### ISSUE THREAD

**Issue by huyhoangk50** [pubkey/eth-crypto#6]
When I import eth-crypto inside truffle test files, then run `truffle test`, it returns error "Cannot find module 'web3/lib/web3/event.js'". It might because inside of the eth-crypto module, web3 is created another time.

**Comment by pubkey** [comment]
I think the problem is that web3 set's itself to window.Web3 but only if that has not been done before. [See](https://github.com/ethereum/web3.js/blob/62dd77c7f43522eb568a001cf4c4df726f8efa69/index.js#L4)

The main thing is that it looks like truffle uses `window.Web3` instead of `require(web3)`.

I will add a fix where eth-crypto only imports the parts of web3 that are needed, not the whole module. This will prevent setting the window-object.

As workarround you can set `window.Web3 = undefined` directly after `require('eth-crypto')`
