### ISSUE TITLE
Recovered address doesn't match

### ISSUE THREAD

**Issue by linusnorton** [pubkey/eth-crypto#9]
Hello,

I am trying to recover an address from a signed message, but when I do this in my truffle test suite the result does not match:

```
contract("TestCase", ([address1]) => {

  it("test recovery", async () => {
    const address2 = EthCrypto.recover(
      web3.eth.sign(address1, EthCrypto.hash.keccak256("a string")),
      EthCrypto.hash.keccak256("a string")
    );

    console.log("address1", address1);
    console.log("address2", address2);
  });

});
```

Example output:

```
address1 0xd2fd17474481dbeb69f73e4a30385100f486c253
address2 0x1bE7a07E5094725208E652f4f045b3eBfB721487
```

Am I using the library in the correct way?

**Comment by pubkey** [comment]
Hi @linusnorton 
When you sign with web3.js, a prefix will be added after the hashing, which is total garbage because it will no longer be possible to recover the signer in solidity.

Use `EthCrypto.sign` like described in the [tutorial](https://github.com/pubkey/eth-crypto/blob/master/tutorials/signed-data.md).


Use

**Comment by projectoblio** [comment]
What? Is this to ensure probabilistic encryption? Can we remove the probabilistic string before recovering the message to get the true address owner? Isn't that the point of this lib? To handle that kind of stuff?

**Comment by projectoblio** [comment]
Tbh that's a thought-provoking comment.  The "prefix" added after the hashing is a necessary security requirement for 99% of encryption applications. Leaving it as non-default might open up a traditional encryption coder to a bunch of security flaws. 

Non-probabilistic encryption is a bit more common in blockchain since the same wallet seed / message might always want to hash to the same address / signature. And people new to encryption would expect this to be the default.

I think there should be a function where a random seed is added to make things probabilistic in addition to the current default functions.

**Comment by projectoblio** [comment]
Wait I just re-read your comment and realized I have no idea what you mean by "adding after the hashing" and "not being recovered in Solidity"
